language: cpp
sudo: required
dist: trusty

compiler:
  - gcc

before_install:
  - sh -c "sudo apt-get install -qq build-essential g++ python-software-properties"
  - sh -c "sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y"
  - sh -c "sudo add-apt-repository ppa:george-edison55/cmake-3.x -y; sudo apt-get update -qq; sudo apt-get install -qq cmake qt-latest -y"

before_script:
  - source /opt/qt58/bin/qt58-env.sh
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make
  - make check

after_success:
  - tar -czf qmlfmt.tar.gz qmlfmt

deploy:
  provider: releases
  api-key: 
    secure: "TImQ2gleoniWmeG4CTGR0aaN+fsU27Bg6yAPK4t1ckI5O56LHYYrNDe6nhC/CEOmpKtT8nkkD53t/2MyheQWKqKUVXFQdk24t5kItOfypsZYMFU8XKmUMaGwMeD2BeI9hOqGISnD3bTgq/2aSX8CPuz8aXk9bkEqtagGNZGc80I="
  file: qmlfmt.tar.gz
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
